### ISSUE TITLE
Husky not working

### ISSUE THREAD

**Issue by roomman** [atej/ember-new-plus#1]
Hi and thanks for this script - so helpful. 

I'm having issues with Husky - commitlint is not firing up. After running the bash file, the only reference to Husky that I could find in my repo was in `.eslintrc.js`. No `husky.config.js` is being generated and Husky is not being installed as a dependency. 

Should I be manually adding these? 

Thanks.

**Comment by atej** [comment]
Hi,

Turns out the file name for the `husky` partial in the grunt config was incorrect. That's been fixed.

You can discard the previous changes and run the script again, or do it manually:

```bash
yarn add husky@^3.1.0
```

./husky.config.js
```javascript
'use strict';

module.exports = {
  hooks: {
    'commit-msg': 'commitlint -E HUSKY_GIT_PARAMS',
  },
};
```

Thanks for checking the script out!

**Comment by roomman** [comment]
Awesome, thanks so much!
